### ISSUE TITLE
Atributos do foguete estão publicos

### ISSUE THREAD

**Issue by EduardoPC05** [ednilsonrossi/ApoloProject#4]
Meu consagrado model @caioslopes , cadê o encapsulamento?

Vamos manter a integridade dos objetos alheios

**Comment by ednilsonrossi** [comment]
Além disso, o objeto é mutável ou imutável?

**Comment by edenilsonjunior** [comment]
Crashou a jdk tb 😭

**Comment by caioslopes** [comment]
foi mal galera, macos aqui salvou jdk nova :/

**Comment by edenilsonjunior** [comment]
tinha que ser java

**Comment by IgorFilipiCardoso** [comment]
tipo assim, o natan resolve né

**Comment by caioslopes** [comment]
👀

**Comment by edenilsonjunior** [comment]
chama o qa

**Comment by roberttiss** [comment]
ficou muito verboso

**Comment by CauaDeSa** [comment]
Refaz em c#

**Comment by edenilsonjunior** [comment]
o cara trabalha com c#, suspeito
